version: '3.8'
services:
  notification_app:
    container_name: notification_app
    build:
      context: '.'
      args:
        - APP_ENV=development
        - COMPOSER_NO_INTERACTION=0
    ports:
      - 3006:80
    networks:
      - demonet  
    volumes:
      - ./app:/app
    command: bash -c "composer update --lock --prefer-source && supervisord"
  
  mysql-server:
    image: mysql:8.0
    container_name: notification-db
    environment:
      MYSQL_DATABASE: notification
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    networks:
      - demonet  
    volumes:
      - mysql_data:/var/lib/mysql:rw   

volumes:
  mysql_data:
   
networks:
  demonet:
    name: app_network
